<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1593315324285" stop="1593315325937">
  <name>TestCase.test_order</name>
  <labels/>
  <test-cases>
    <test-case start="1593315324285" status="failed" stop="1593315325937">
      <description>
        用例描述：购买单个产品-匹配单个计费项下多个策略-支付订单
        </description>
      <name>TestOrder.test_order_01</name>
      <failure>
        <message>AssertionError: assert False
 +  where False = &lt;bound method Assertions.assert_in_text of &lt;Common.Assert.Assertions object at 0x10abdee48&gt;&gt;({'body': {'code': 13, 'details': [{'@type': 'type.googleapis.com/newbilling.ErrorDetail', 'cause': '调用GetCosts接口失败', '...newbilling.ErrorDetail","error_name":"create_order_failed","cause":"调用GetCosts接口失败"}]}', 'time_consuming': 584.06, ...}, 'order_id')
 +    where &lt;bound method Assertions.assert_in_text of &lt;Common.Assert.Assertions object at 0x10abdee48&gt;&gt; = &lt;Common.Assert.Assertions object at 0x10abdee48&gt;.assert_in_text</message>
        <stack-trace>self = &lt;TestCase.test_order.TestOrder object at 0x10abde208&gt;

    @pytest.allure.feature('购买产品支付订单场景1')
    @allure.severity('blocker')
    def test_order_01(self):
        """
            用例描述：购买单个产品-匹配单个计费项下多个策略-支付订单
            """
        data = Order()
        urls = data.url
        params = data.data
        header = data.header
        request = Request.Request()
        Asserts = Assert.Assertions()
        conf = Config()
        host = conf.host
        req_url = 'http://' + host
        api_url = req_url + urls[0]
        # sqlinfo = Mysql.Mysqlconnect()
    
        #创建订单
    
        response = request.post_request(api_url, params[0], header[0])
&gt;       assert Asserts.assert_in_text(response, 'order_id')
E       assert False
E        +  where False = &lt;bound method Assertions.assert_in_text of &lt;Common.Assert.Assertions object at 0x10abdee48&gt;&gt;({'body': {'code': 13, 'details': [{'@type': 'type.googleapis.com/newbilling.ErrorDetail', 'cause': '调用GetCosts接口失败', '...newbilling.ErrorDetail","error_name":"create_order_failed","cause":"调用GetCosts接口失败"}]}', 'time_consuming': 584.06, ...}, 'order_id')
E        +    where &lt;bound method Assertions.assert_in_text of &lt;Common.Assert.Assertions object at 0x10abdee48&gt;&gt; = &lt;Common.Assert.Assertions object at 0x10abdee48&gt;.assert_in_text

TestCase/test_order.py:35: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="feature" value="购买产品支付订单场景1"/>
        <label name="severity" value="blocker"/>
        <label name="thread" value="28154-MainThread"/>
        <label name="host" value="wangxiaingdembp"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
